#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

/* tools packages */

#define PKG_EASYFLASH_ENV
#define PKG_EASYFLASH_IAP
#define PKG_EASYFLASH_LOG
#define PKG_EASYFLASH_WRITE_GRAN 64
#define PKG_EASYFLASH_ENV_USING_WL_MODE
#define PKG_EASYFLASH_ENV_USING_LEGACY_MODE
#define PKG_EASYFLASH_ENV_USING_PFS_MODE
#define PKG_EASYFLASH_ENV_SETTING_SIZE 2048
#define PKG_EASYFLASH_LOG_AREA_SIZE 16384
#define PKG_EASYFLASH_ENV_AUTO_UPDATE
#define PKG_EASYFLASH_ENV_VER_NUM 0
#define PKG_EASYFLASH_ERASE_GRAN 4096
#define PKG_EASYFLASH_START_ADDR 0

/* system packages */

#define FAL_DEBUG 1
#define FAL_PART_HAS_TABLE_CFG

/* Board extended module Drivers */

#endif
